config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :forum_sections
  resources :forum_topics do
    resources :comments
    resources :votes
  end
  resources :users

  get 'pages/home'

  match ':controller(/:action(:id))', :via => :get

  root 'pages#home'

end

app/models/forum_topic.rb
# a ForumTopic class
class ForumTopic < ActiveRecord::Base
  belongs_to :forum_section
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5, maximum: 40 }

  def add_comment(comment)
    update_attributes comments: comments.push(comment)
  end

  def delete_comment(comment_id, user)
    comment = Comment.find(comment_id)
    comments.destroy(comment) if comment.can_delete?(user)
    save
  end

  def comments_amount
    (comments || []).size
  end

  def votes_diff
    upvotes - downvotes
  end

  def vote_list
    votes || []
  end

  def total_votes
    vote_list.size
  end

  def upvotes
    values = Vote.where('forum_topic_id = ? and vote_type = ?',
                        self[:id].to_s, '+')
    (values || []).size
  end

  def downvotes
    values = Vote.where('forum_topic_id = ? and vote_type = ?',
                        self[:id].to_s, '-')
    (values || []).size
  end

  def upvote(user)
    vote(user: user, vote_type: '+')
  end

  def downvote(user)
    vote(user: user, vote_type: '-')
  end

  def vote(vote_opts)
    if contains_vote?(vote_opts[:user])
      update_existing_vote(vote_opts)
    else
      add_new_vote(vote_opts)
    end
  end

  def update_existing_vote(vote_opts)
    user = vote_opts[:user]
    return unless contains_vote? user
    vote = user_vote user
    vote.change_type vote_opts[:vote_type] if vote
  end

  def add_new_vote(vote_opts)
    vote_type = vote_opts[:vote_type]
    return unless Vote.valid_type vote_type
    vote_obj = Vote.create(user: vote_opts[:user], forum_topic: self,
                           vote_type: vote_type)
    update_attributes votes: votes.push(vote_obj)
  end

  def contains_vote?(user)
    Vote.where('forum_topic_id = ? and user_id = ?',
               self[:id].to_s, user.id).size > 0
  end

  def user_vote(user)
    Vote.where('forum_topic_id = ? and user_id = ?',
               self[:id].to_s, user.id)[0]
  end
end

app/controllers/forum_topics_controller.rb
class ForumTopicsController < ApplicationController
  before_action :set_forum_topic, only: [:show, :edit, :update, :destroy]

  # GET /forum_topics
  # GET /forum_topics.json
  def index
    @forum_topics = ForumTopic.all
  end

  # GET /forum_topics/1
  # GET /forum_topics/1.json
  def show
  end

  # GET /forum_topics/new
  def new
    @forum_topic = ForumTopic.new
  end

  # GET /forum_topics/1/edit
  def edit
  end

  # POST /forum_topics
  # POST /forum_topics.json
  def create
    @forum_topic = ForumTopic.new(forum_topic_params)

    respond_to do |format|
      if @forum_topic.save
        format.html { redirect_to @forum_topic, notice: 'Forum topic was successfully created.' }
        format.json { render :show, status: :created, location: @forum_topic }
      else
        format.html { render :new }
        format.json { render json: @forum_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forum_topics/1
  # PATCH/PUT /forum_topics/1.json
  def update
    respond_to do |format|
      if @forum_topic.update(forum_topic_params)
        format.html { redirect_to forum_topic_path(@forum_topic), notice: 'Forum topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum_topic }
      else
        format.html { render :edit }
        format.json { render json: @forum_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forum_topics/1
  # DELETE /forum_topics/1.json
  def destroy
    @forum_topic.destroy
    respond_to do |format|
      format.html { redirect_to forum_topics_url, notice: 'Forum topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum_topic
      @forum_topic = ForumTopic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_topic_params
      params.require(:forum_topic).permit(:title, :forum_section_id, :creator_id)
    end
end

app/helpers/forum_topics_helper.rb
# module
module ForumTopicsHelper
end

app/views/forum_topics/_form.html.erb
<%= form_for(@forum_topic) do |f| %>
  <% if @forum_topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_topic.errors.count, "error") %> prohibited this forum_topic from being saved:</h2>

      <ul>
      <% @forum_topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :forum_section_id %><br>
    <%= f.number_field :forum_section_id %>
  </div>
  <div class="field">
    <%= f.label :creator_id %><br>
    <%= f.number_field :creator_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forum_topics/edit.html.erb
<h1>Editing Forum Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum_topic %> |
<%= link_to 'Back', forum_topics_path %>

app/views/forum_topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forum Topics</h1>

<table class="pretty-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Forum section</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forum_topics.each do |forum_topic| %>
      <tr>
        <td><%= forum_topic.title %></td>
        <td><%= forum_topic.forum_section_id %></td>
        <td><%= forum_topic.creator_id %></td>
        <td class="options"><%= link_to 'Show', forum_topic %></td>
        <td class="options"><%= link_to 'Edit', edit_forum_topic_path(forum_topic) %></td>
        <td class="options"><%= link_to 'Destroy', forum_topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forum topic', new_forum_topic_path %>

app/views/forum_topics/new.html.erb
<h1>New Forum Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_topics_path %>

app/views/forum_topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @forum_topic.title %>
</p>

<p>
  <strong>Forum section:</strong>
  <%= @forum_topic.forum_section_id %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @forum_topic.creator_id %>
</p>

<h2>Comments</h2>
<table class="pretty-table">
  <thead>
    <th>Author id</th>
    <th>Comment</th>
    <th>Date</th>
  </thead>
  <tbody>
    <% @forum_topic.comments.each do |comment| %>
      <tr>
        <td><%= comment.author_id %></td>
        <td><%= comment.contents %></td>
        <td><%= comment.updated_at.strftime('%F %T') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Add a Comment</h2>
<%= form_for([@forum_topic, @forum_topic.comments.build]) do |f| %>
  <p>
    <%= f.label :author_id %><br/>
    <%= f.number_field :author_id %>
  </p>

  <p>
    <%= f.label :contents %><br/>
    <%= f.text_field :contents %>
  </p>

  <p><%= f.submit %></p>

<% end %>

<%= link_to 'Edit', edit_forum_topic_path(@forum_topic) %> |
<%= link_to 'Back', forum_topics_path %>