config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :forum_sections
  resources :forum_topics do
    resources :comments
    resources :votes
  end
  resources :users

  get 'pages/home'

  match ':controller(/:action(:id))', :via => :get

  root 'pages#home'

end

app/models/message.rb
# a Message class
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  validates :thread_id, presence: true
  validates :topic, presence: true, length: { maximum: 30 }
  validates :contents, presence: true, length: { maximum: 180 }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:thread_id, :topic, :sender_id, :recipient_id, :contents, :is_read)
    end
end

app/helpers/messages_helper.rb
# module
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :thread_id %><br>
    <%= f.text_field :thread_id %>
  </div>
  <div class="field">
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :sender_id %><br>
    <%= f.text_field :sender_id %>
  </div>
  <div class="field">
    <%= f.label :recipient_id %><br>
    <%= f.text_field :recipient_id %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_field :contents %>
  </div>
  <div class="field">
    <%= f.label :is_read %><br>
    <%= f.check_box :is_read %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Thread</th>
      <th>Topic</th>
      <th>Sender</th>
      <th>Recipient</th>
      <th>Contents</th>
      <th>Is read</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.thread_id %></td>
        <td><%= message.topic %></td>
        <td><%= message.sender_id %></td>
        <td><%= message.recipient_id %></td>
        <td><%= message.contents %></td>
        <td><%= message.is_read %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Thread:</strong>
  <%= @message.thread_id %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @message.topic %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender_id %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @message.recipient_id %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @message.contents %>
</p>

<p>
  <strong>Is read:</strong>
  <%= @message.is_read %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>