config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :forum_sections
  resources :forum_topics do
    resources :comments
    resources :votes
  end
  resources :users

  get 'pages/home'

  match ':controller(/:action(:id))', :via => :get

  root 'pages#home'

end

app/models/forum_section.rb
# a ForumSection class
class ForumSection < ActiveRecord::Base
  has_many :forum_topics, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5, maximum: 40 }
  validates :minimum_required_role, inclusion: %w(USER MOD ADMIN)
end

app/controllers/forum_sections_controller.rb
class ForumSectionsController < ApplicationController
  before_action :set_forum_section, only: [:show, :edit, :update, :destroy]

  # GET /forum_sections
  # GET /forum_sections.json
  def index
    @forum_sections = ForumSection.all
  end

  # GET /forum_sections/1
  # GET /forum_sections/1.json
  def show
  end

  # GET /forum_sections/new
  def new
    @forum_section = ForumSection.new
  end

  # GET /forum_sections/1/edit
  def edit
  end

  # POST /forum_sections
  # POST /forum_sections.json
  def create
    @forum_section = ForumSection.new(forum_section_params)

    respond_to do |format|
      if @forum_section.save
        format.html { redirect_to @forum_section, notice: 'Forum section was successfully created.' }
        format.json { render :show, status: :created, location: @forum_section }
      else
        format.html { render :new }
        format.json { render json: @forum_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forum_sections/1
  # PATCH/PUT /forum_sections/1.json
  def update
    respond_to do |format|
      if @forum_section.update(forum_section_params)
        format.html { redirect_to @forum_section, notice: 'Forum section was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum_section }
      else
        format.html { render :edit }
        format.json { render json: @forum_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forum_sections/1
  # DELETE /forum_sections/1.json
  def destroy
    @forum_section.destroy
    respond_to do |format|
      format.html { redirect_to forum_sections_url, notice: 'Forum section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum_section
      @forum_section = ForumSection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_section_params
      params.require(:forum_section).permit(:title, :minimum_required_role)
    end
end

app/helpers/forum_sections_helper.rb
# module
module ForumSectionsHelper
end

app/views/forum_sections/_form.html.erb
<%= form_for(@forum_section) do |f| %>
  <% if @forum_section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_section.errors.count, "error") %> prohibited this forum_section from being saved:</h2>

      <ul>
      <% @forum_section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :minimum_required_role %><br>
    <%= f.select :minimum_required_role, %w(USER MOD ADMIN) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forum_sections/edit.html.erb
<h1>Editing Forum Section</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum_section %> |
<%= link_to 'Back', forum_sections_path %>

app/views/forum_sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forum Sections</h1>

<table class="pretty-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Minimum required role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forum_sections.each do |forum_section| %>
      <tr>
        <td><%= forum_section.title %></td>
        <td><%= forum_section.minimum_required_role %></td>
        <td class="options"><%= link_to 'Show', forum_section %></td>
        <td class="options"><%= link_to 'Edit', edit_forum_section_path(forum_section) %></td>
        <td class="options"><%= link_to 'Destroy', forum_section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forum section', new_forum_section_path %>

app/views/forum_sections/new.html.erb
<h1>New Forum Section</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_sections_path %>

app/views/forum_sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @forum_section.title %>
</p>

<p>
  <strong>Minimum required role:</strong>
  <%= @forum_section.minimum_required_role %>
</p>

<%= link_to 'Edit', edit_forum_section_path(@forum_section) %> |
<%= link_to 'Back', forum_sections_path %>